SWDEV-135 add k8s deploy yaml and circleci automation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,6 +22,15 @@ jobs:
           name: "Log in to AWS ECR"
           command: eval $(aws ecr get-login --no-include-email --region us-west-2)
       - run:
+          name: Install Kops and Kubectl
+          command: |
+            wget -O kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
+            chmod +x ./kops
+            sudo mv ./kops /usr/local/bin/kops
+            wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
+            chmod +x ./kubectl
+            sudo mv ./kubectl /usr/local/bin/kubectl      
+      - run:
           name: "Build & Push Docker Image"
           command: |
             BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
@@ -30,11 +39,14 @@ jobs:
             if [[ ($BRANCH_NAME == "develop") ]]
             then
               BRANCH_NAME="dev"
+              K8S_CLUSTER="stage.hub"
             elif [[ ($BRANCH_NAME == "master") ]]
             then
               BRANCH_NAME="stage"
+              K8S_CLUSTER="hub"
             else
               BRANCH_NAME="feat"
+              K8S_CLUSTER="dev.hub"
             fi
 
             declare -a component_arr=("dccn-hub-taskmgr" "dccn-hub-api" "dccn-hub-usermgr" "dccn-hub-email")
@@ -51,4 +63,14 @@ jobs:
                 docker tag ${component_arr[$i]}:$BRANCH_NAME $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/${component_arr[$i]}:$TAG
                 docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/${component_arr[$i]}:$TAG
               done
+            done
+            declare -a deployment_arr=("taskmgr" "usermgr" "email" "api")
+            kops export kubecfg --name ${K8S_CLUSTER}.k8s.ankr.network --state s3://kops.${K8S_CLUSTER}.config
+            for ((i=0; i<arrlen; i++)); do
+              kubectl patch deployment/${deployment_arr[$i]} -p \
+              '{"spec":{"template":{"spec":{"containers":[{"name":"'${deployment_arr[$i]}'","image":"'${AWS_ACCOUNT}'.dkr.ecr.'${AWS_REGION}'.amazonaws.com/'${component_arr[$i]}':'${BRANCH_NAME}'"}]}}}}'
+              if ! kubectl rollout status deploy/${deployment_arr[$i]}; then
+                echo "Deploy failed, roll back to previous version"
+                kubectl rollout undo deploy/${deployment_arr[$i]} 
+              fi
             done
